### ISSUE TITLE
[Share Data] Fill in the metadata - Dropdown / Tag input

### ISSUE THREAD

**Issue by ChaimaaZaoui** [okp4/dataverse-portal#422]
As a user, I want to be able to fill in the metadata of the dataset so that it's properly referenced in the dataverse once uploaded.

### Scenario 1 : Dropdown & Tag input Modal for the "+n"
**Given that** I have entered in a field more items than it can support in the UI
**Then** the last item in the field is a "+n" item
**When** I click on the "+n" 
**Then** a modal opens displaying the hidden Items

The used modal is identical to the one used to display paragraphs in Governance : #218

**Comment by fredericvilcot** [comment]
@AnjaMis 
Please, could you add the technical spec related to a new `Modal` component, designed from scratch?

**Comment by AnjaMis** [comment]
## Technical Specification: Modal Component for Displaying Hidden Items

### Description

The Modal Component is responsible for displaying hidden items that couldn't be shown in the UI due to space limitations. When the user has entered more items than can be displayed in the field, a "+n" item is shown, indicating there are hidden items. Clicking on the "+n" item opens the modal, revealing all the hidden items.

### Modal Component (ModalDialog)

### Props

- `isOpen` (boolean, required): Determines whether the modal is open or not.
- `onClose` (function, required): A callback function to close the modal when the close button is clicked or when clicking outside the modal.
- `hiddenItems` (array, required): An array containing the hidden items to be displayed in the modal.
- `title` (string, required): The title of the modal, which serves as a label for the input field.

### Usage

1. When rendering the main container component (the parent component containing the form summary answers and other components), maintain a state that tracks whether the modal is open or closed, e.g., `isModalOpen: boolean`, and an array to store the hidden items, e.g., `hiddenItems: []`.
2. When the user has entered more items than can be shown in the UI, create the "+n" item and display it in the field, indicating that there are hidden items.
3. When the "+n" item is clicked, set the `isModalOpen` state to true and populate the `hiddenItems` state array with the hidden items that couldn't be shown in the field.
4. Render the ModalDialog component conditionally based on the `isModalOpen` state. Pass the following props:
    - `isOpen`: Set to the `isModalOpen` state value.
    - `onClose`: A function to update the `isModalOpen` state to false.
    - `hiddenItems`: The `hiddenItems` state array.
    - `title`: The label of the input field, serving as the title of the modal.
5. The ModalDialog component should display the `hiddenItems` passed as props. The modal should have a title that matches the `title` prop.
6. When the modal is open, users can review the hidden items. When they click the close button or click outside the modal, the modal should be closed by calling the `onClose` prop function, updating the `isModalOpen` state to false.

**Comment by lolottetheclash** [comment]
@AnjaMis thank you for this detailed specification!
The problem you'll find here is that the design of this component leads to an overly specific result.
You've defined a mandatory `hiddenItems` prop as being a list of "hidden" items: this is true for this feature, as we're trying to display hidden items through the modal. 
But it's not always a question of hidden items as described here, but rather of "content" to be displayed to the user (which won't necessarily be an array of items).
Similarly, if we want to use this modal elsewhere, it's not certain that we need a title to display.
You can take a look at other libraries such as [MUI](https://mui.com/material-ui/react-modal/) or [ChakraUi](https://chakra-ui.com/docs/components/modal) to see how to build this modal to make it generic 🚀

**Comment by AnjaMis** [comment]
@lolottetheclash good point! I have updated my previous comment now! :)

**Comment by 0xLodz** [comment]
@AnjaMis thanks,  that's a very detailed specification! 👍

In order to make it easier to write the specification, we can take a step back and discuss about the definition of the Modal, that influences how we orient the specification description.
Indeed, the modal might also be used to alert the user or invite him to perform a specific action. That additional definition helps to define it's functionalities by detaching it's usage from the context we primarily need (revealing hidden items).

The modal component would probably need a third parameter for it's JSX content. I think we need to define it even though we use the default React `children` property.

Also, modal use to be displayed at the top of the App (e. g. our [Notification](https://github.com/okp4/dataverse-portal/blob/main/src/ui/App.tsx#L33) component), mainly because of [styling considerations](https://css-tricks.com/considerations-styling-modal/).
You can achieve that using [createPortal API](https://react.dev/reference/react-dom/createPortal).

**Comment by fredericvilcot** [comment]
Thx @AnjaMis :)
I think you must consider going a little bit further in the specification, especially regarding the way the modal behaves.
E.G. Should we close the modal on click outside?, on pressing escape button?, should we add a way to disable these options? How the user could customize the viewport's background behind the modal? ...
Don't hesitate to have a look at other UI libraries ;)

**Comment by lolottetheclash** [comment]
Nice improvements! I think you forgot the `children` prop, and also you can replace both classnames by a `classes` object, as we made in some of our components, it's more flexible to apply style where we want :)

**Comment by ChaimaaZaoui** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DEV-board--63e210cc9b1f2f73ee3f4e5f/issues/okp4/dataverse-portal/422?planning-poker) with Zenhub @fredericvilcot @0xLodz @AnjaMis @lolottetheclash
