### ISSUE TITLE
Rework color palette

### ISSUE THREAD

**Issue by 0xLodz** [okp4/dataverse-portal#481]
# Enhancement/ Color palette

As a developer,
I want to quickly retrieve colors related to the project's design system, using colors palettes.
So that I can easily define colors for new pages or components.

## Tech specs
- implement color palette based on Design System colors, by following guidelines from [this discussion](https://github.com/okp4/dataverse-portal/discussions/462).

**Comment by 0xLodz** [comment]
@SpicySalm0n color defined for dataset card text (cf screenshot) doesn't belong to design system colors.

Could you please add it to the design system or provide an alternative color already defined in the design system? Thanks

![image](https://github.com/okp4/dataverse-portal/assets/8344874/0cccf191-e3d8-4e92-abcd-3d57103d6c20)

**Comment by SpicySalm0n** [comment]
@0xLodz 
Hi, yes, it was done before the color system change, 
I suggest changing the color to avoid a single addition.
I chose turquoise 200 (#80DADB). Getting too close to the color of the zones, I also suggest modifying the color of the zones with turquoise 700 (#009898) instead of turquoise 500 (#00B6B7) to accentuate the difference. What do you think ?

**Comment by 0xLodz** [comment]
@SpicySalm0n sounds great!

The palette will be updated according to your suggestion.

Thanks
