### ISSUE TITLE
Feat : Catalog – Resource Filters  

### ISSUE THREAD

**Issue by henigh** [okp4/dataverse-portal#88]
# Feat : Catalog – Resource Filters  

> **As a** user of the portal,
> **I want** to be able to filter by dataverse item (Dataspace // Dataset // Service) 
> **So that** I can have be more specific about what I'm looking for

### Scenario: default display (desktop)

**Given that** I am a user of the web portal (authenticated or unauthenticated),
**When** I am on the dataverse page, 
**Then** I should be able to use a filter that can be applied to the type of dataverse item (Data Space or Dataset or Service)

### Scenario: mobile display 

**Given that** I am a user of the web portal (authenticated or unauthenticated),
**When** I am on the dataverse page, 
**And** I use a mobile device
**Then** I should be able to see and interact with filters in a mobile-friendly way.

### Scenario: Interacting with filters

**Given that** I am a user of the web portal (authenticated or unauthenticated),
**When** I click on `all`
**Then** All types of `dataverse items` should appear
**When** I click on `Data Spaces`
**Then** Only `Data Spaces` will appear
**When** I click on `Datasets`
**Then** Only `Datasets` will appear
**When** I click on `Services`
**Then** Only `Services` will appear
**When** I click on 2 types
**Then** Only cards of these two types will appear
**When** I deselect 1 specific type
**Then** `all` is selected automatically

### Mockups
Desktop : 
![image.png](https://images.zenhubusercontent.com/617955902b89e7481066da3f/4c0e2a7c-f5d9-4bb3-81f7-7e5309f5cbbf)

Mobile : 
![image.png](https://images.zenhubusercontent.com/617955902b89e7481066da3f/82e39254-4dcc-4eb1-b123-a01c338814a2)

### Environment

- staging URL: <https://app.staging.okp4.network/>

## Additional informations

None.

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=1206542062) by [Unito](https://www.unito.io)

**Comment by MdechampG** [comment]
Test 24/03/23

Desktop : Firefox, Chrome, Safari
Mobile : Safari 

Scenario : Default display : OK ✅

**Comment by lolottetheclash** [comment]
As seen with @SpicySalm0n @MdechampG & @ErikssonJoakim, the filters are made to wrap on the next line on the small screen instead of staying on one line (as originally planned by the
 original figma), and they can contain text on 2 lines maximum, with an ellipse in case of longer text.
 
 It will now look like that:
 
![Capture d’écran 2023-03-29 à 12 04 58](https://user-images.githubusercontent.com/35332974/228500511-256739d5-3d1e-4a15-8a03-cc110b40b25a.png)

and here is a simulation of long text:  

![Capture d’écran 2023-03-29 à 12 04 27](https://user-images.githubusercontent.com/35332974/228500357-3a478873-b47d-4a6d-be80-b3f27310a742.png)

**Comment by MdechampG** [comment]
Test 06/04/23

Desktop : Firefox, Chrome, Safari
Mobile : Safari (iPhone 12)

Scenario : Default display : OK ✅

Scenario : Mobile display : OK ✅
